drop table FLUGHAFEN cascade constraints;
drop table FLUGHAFENVTWO cascade constraints;
drop table FLUGHAFENVTHREE cascade constraints;
drop table FLUGLINIEHTWO cascade constraints;
drop table FLUGLINIEHTHREE cascade constraints;

drop table FLUGHAFENDFKD cascade constraints;
drop table FLUGHAFENDFKVTWO cascade constraints;
drop table FLUGHAFENDFKVTHREE cascade constraints;
drop table FLUGHAFENDFKHTWO cascade constraints;
drop table FLUGHAFENDFKHTHREE cascade constraints;

drop table FLUGHAFENVTWOFKDEFAULT cascade constraints;
drop table FLUGHAFENVTWOFKVTWO cascade constraints;
drop table FLUGHAFENVTWOFKVTHREE cascade constraints;
drop table FLUGHAFENVTWOFKHTWO cascade constraints;
drop table FLUGHAFENVTWOFKHTHREE cascade constraints;

drop table FLUGHAFENVTHREEFKDEFAULT cascade constraints;
drop table FLUGHAFENVTHREEFKVTWO cascade constraints;
drop table FLUGHAFENVTHREEFKVTHREE cascade constraints;
drop table FLUGHAFENVTHREEFKHTWO cascade constraints;
drop table FLUGHAFENVTHREEFKHTHREE cascade constraints;

drop table FLUGLINIEHTWOFKD cascade constraints;
drop table FLUGLINIEHTWOFKHTWO cascade constraints;
drop table FLUGLINIEHTWOFKHTHREE cascade constraints;
drop table FLUGLINIEHTWOFKVTWO cascade constraints;
drop table FLUGLINIEHTWOFKVTHREE cascade constraints;

drop table FLUGLINIEHTHREEFKD cascade constraints;
drop table FLUGLINIEHTHREEFKHTWO cascade constraints;
drop table FLUGLINIEHTHREEFKHTHREE cascade constraints;
drop table FLUGLINIEHTHREEFKVTWO cascade constraints;
drop table FLUGLINIEHTHREEFKVTHREE cascade constraints;
