CREATE TABLE Meta_Table_Partition(
table_id NUMBER GENERATED by default on null as IDENTITY,
table_name VARCHAR(40) NOT NULL UNIQUE,
partition_type VARCHAR(1),
CONSTRAINT Meta_Table_Partition_PS PRIMARY KEY (table_id)
);

CREATE SEQUENCE mtp_seq start with 1 increment by 1 nomaxvalue;

CREATE TABLE Meta_Columns(
column_id NUMBER GENERATED by default on null as IDENTITY,
table_id NUMBER,
column_name VARCHAR(50),
column_type VARCHAR(20),
column_default VARCHAR(100),
database_id INTEGER,
CONSTRAINT Meta_Columns_PS
		PRIMARY KEY (column_id),
CONSTRAINT Meta_Columns_FS
		FOREIGN KEY (table_id) REFERENCES Meta_Table_Partition (table_id)
);

CREATE TABLE Meta_Table_Constraints_Between(
between_constraint_id NUMBER GENERATED by default on null as IDENTITY,
min_type VARCHAR(25),
min_value VARCHAR(50),
max_type VARCHAR(25),
max_value VARCHAR(50),
CONSTRAINT Meta_Table_Between_PS
                PRIMARY KEY (between_constraint_id) 
);

CREATE TABLE Meta_Table_Constraints_Binary(
binary_constraint_id NUMBER GENERATED by default on null as IDENTITY,
operator VARCHAR(5),
binary_type VARCHAR(5),
left_column_name VARCHAR(50),
left_column_type VARCHAR(20),
right_literal_value VARCHAR(50),
right_literal_type VARCHAR(20),
CONSTRAINT Meta_Table_Binary_PS
                PRIMARY KEY (binary_constraint_id)
);

CREATE TABLE Meta_Table_Constraints(
table_id NUMBER,
database_id INTEGER,
constraint_name VARCHAR(100),
constraint_type VARCHAR(5),
constraint_attribute VARCHAR(100),
constraint_table_ref VARCHAR(100),
constraint_table_ref_attribute VARCHAR(100),
between_constraint_id INTEGER,
binary_constraint_id INTEGER,
CONSTRAINT Meta_Table_Constraints_PS
		PRIMARY KEY (table_id, database_id, constraint_name),
CONSTRAINT Meta_Table_Constraints_FS
		FOREIGN KEY (table_id) REFERENCES Meta_Table_Partition (table_id),
CONSTRAINT Meta_Table_Between_FS
                FOREIGN KEY (between_constraint_id) REFERENCES Meta_Table_Constraints_Between (between_constraint_id),
CONSTRAINT Meta_Table_Binary_FS
                FOREIGN KEY (binary_constraint_id) REFERENCES Meta_Table_Constraints_Binary (binary_constraint_id)
);

CREATE TABLE Meta_Horizontal(
horizontal_id NUMBER GENERATED by default on null as IDENTITY,
table_id NUMBER,
attribute_name VARCHAR(10),
attribute_type VARCHAR(25),
value_lowest VARCHAR(50),
value_highest VARCHAR(50),
value_default VARCHAR (50),
database_id INTEGER,
CONSTRAINT Meta_Horizontal_PS
		PRIMARY KEY (horizontal_id),
CONSTRAINT Meta_Horizontal_FS
		FOREIGN KEY (table_id) REFERENCES Meta_Table_Partition (table_id)
);

